# Generated by Django 3.2 on 2021-08-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_subscriber_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='img',
            field=models.ImageField(default='/static/imgs/enquiry.jpg', null=True, upload_to='subs/'),
        ),
    ]
