# Generated by Django 3.2 on 2021-08-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_subplan_validity_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='reg_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
