# Generated by Django 3.2 on 2021-09-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_trainermsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainermsg',
            name='user_type',
            field=models.CharField(blank=True, default='admin', max_length=100),
        ),
    ]
