# Generated by Django 3.2 on 2021-09-11 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0040_trainersubscriberreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainersubscriberreport',
            name='report_from_trainer',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_from_trainer', to='main.trainer'),
        ),
        migrations.AlterField(
            model_name='trainersubscriberreport',
            name='report_from_user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_from_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
